version: '3'
services:
  db:
    container_name: db-container
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nginx-desafio_network

  app-node:
    depends_on:
      - db
    build:
      context: node
    container_name: node_app
    #entrypoint: wait-for database:3306 -t 40 -- ./start.sh
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
    ports:
      - "3000:3000"
    networks:
      - nginx-desafio_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-desafio_network

networks:
  nginx-desafio_network:
    driver: bridge

volumes:
  db_data:
